// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include "fileuv.h"

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

listener_data_t *listen(const char* path);
RcppExport SEXP _fileuv_listen(SEXP s_path) {
BEGIN_RCPP
    SEXP xptr;
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type path(s_path);
    listener_data_t *listener_data_ptr = listen(path);
    xptr = R_MakeExternalPtr(listener_data_ptr, R_NilValue, s_path);
    R_PreserveObject(xptr);
    return xptr;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fileuv_listen", (DL_FUNC) &_fileuv_listen, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_fileuv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
